#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/rezervacny_system
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximumPoolSize=2



#logs off
#spring.main.banner-mode=OFF
#logging.level.root=OFF
#logging.level.org=OFF
#logging.level.org.springframework=OFF
#logging.level.org.hibernate=OFF
#logging.level.com.zaxxer.hikari=OFF



#JPA
#-------Hibernate------
#spring.jpa.hibernate.ddl-auto=create-drop
#spring.jpa.hibernate.ddl-auto=create
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
#spring.jpa.properties.hibernate.format_sql=false
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect



#Thymeleaf
spring.thymeleaf.cache=false



#Server
server.port=8080
